### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by theskumar** [pythonindia/junction#133]
**Goal**: 
- make reviewer's section functional.
- polishing of UI elements.

Changeset: https://github.com/pythonindia/junction/compare/0.1.0...master

---

__Added__
- [x] add support for fig based development environment (#129)
- [x] django admin got a new theme based on django-flat-theme
- [x] setup social sharing on proposal detail pages (#185)
- [x] add `SITE_URL` settings to support path based root url of site. 
- [x] add docker/fig setup
- [x] add celery support
- [x] send mail to reviewers for new proposals

__Changes__
- [x] hide reviewer name in comments (#193)
- [x] UI: remove 'description' from page proposals list (#149)
- [x] update styling of create proposal forms

__Fixes__
- [x] upgrade django and other libraries to latest
- [x] fix incorrect login url on comment section

**Comment by kracekumar** [comment]
Can we make the release ?

**Comment by theskumar** [comment]
updated changelog, will make 0.2.0 release and let you know.

**Comment by theskumar** [comment]
all set. Please close this story when you are done. Find the next release tracker here: https://github.com/pythonindia/junction/issues/196
