### ISSUE TITLE
Test and upgrade to Django 1.8

### ISSUE THREAD

**Issue by theskumar** [pythonindia/junction#201]
Since 1.8 is a LTS release, it would make sense to upgrade to 1.8 as soon as possible.

**TODO (as I see):** 
- [ ] check against each of the third party dependencies whether they are compatible with 1.8
- [ ] more integration tests before upgrade would be helpful
- [ ] _add more here..._

**Comment by ChillarAnand** [comment]
lets move to py3?

**Comment by theskumar** [comment]
@ChillarAnand :) sure thing, but practicality beats purity. It can be handled/tracked in another issue. These are few of my concerns, apart from the all the goodness of py3.

1. Lack of test coverage
2. Most of the developers (including me) have not yet migrated to py3 fully, because if we want to move to py3, maintaining it for py2 would not be good idea. This would mean completely py3. So I see a little community onboarding friction here.

Summarising, py3 would be nice to have, but I think we have scope to wait for it a bit. But definitely it requires a different ticket. :)

**Comment by kracekumar** [comment]
We're on Django 1.8.
